import Head from 'next/head'
import Link from "next/link";
import { getAllPosts } from '../lib/data'

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {
            posts.map(item => (
              <div key={item.slug}>
                <Link href={`/blog/${item.slug}`}>
                  <a><h3>{item.title}</h3></a>
                </Link>
                <p>{item.date}</p>
                <p>{item.content}</p>
              </div>
            ))
          }
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const allPosts = getAllPosts();
  return {
    props: {
      posts: allPosts.map(({data, slug, content}) => ({
        ...data,
        date: data.date.toISOString(),
        slug,
        content
      }))
    }
  }
}
